services:
  db:
    ports: []

  backend:
    ports: []
    env_file:
      - ./backend/.env.prod
    environment:
      DATABASE_URL: postgresql+asyncpg://tournament:${POSTGRES_PASSWORD}@db:5432/tournament_db

  frontend:
    ports:
      - "127.0.0.1:15173:80"
