services:
  tournament-db:
    ports: []

  backend:
    ports: []
    env_file:
      - ./backend/.env.prod
    environment:
      DATABASE_URL: postgresql+asyncpg://tournament:${POSTGRES_PASSWORD}@interclasses-tournament-db-1:5432/tournament_db

  frontend:
    ports: []
    networks:
      default:
      caddy:
        aliases:
          - interclasses-frontend

networks:
  caddy:
    external: true
